### ISSUE TITLE
[Feature Requests] Screenshot

### ISSUE THREAD

**Issue by Aloento** [hozuki/MonoGame.Extended2#5]
Ever considered packing a MonoGame screenshot feature?

**Comment by hozuki** [comment]
Maybe. I wrote a screenshot implementation before. It basically does these:

1. switch to another render target (such as a `Texture2D`);
2. render current frame again;
3. save the contents in the render target to somewhere.

It's not that complicated. After getting the raw image data it's up to you to decide how to deal with it. In the old days `SaveAsPng()` didn't work so I copy the data to a `System.Drawing.Bitmap` (mind the color components!) to do the saving.
